name = "FeatureImportance"
uuid = "1df5a206-fba2-4d4e-8834-780d3dbcc48d"
authors = ["Li Xiang <lxlim2002@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
